### ISSUE TITLE
Managed to end up with 4 WR and no TE

### ISSUE THREAD

**Issue by Samze** [ishakir/shakitz-fantasy-football#78] opened 2016-09-22 18:51 UTC
![image](https://cloud.githubusercontent.com/assets/385176/18761683/de18beca-80fd-11e6-9da0-6c7780fcde9e.png)

**Comment by Samze** [comment] 2016-09-22 19:16
Looks like this happens if I do the swap in a particular order. It lets me go from Wallace(WR) to Pitta(TE), but not from Pitta(TE) to Wallace(WR)

**Comment by ishakir** [comment] 2016-09-22 20:18
Dear Sir,

I have passed your query on to our front end specialists who are currently reviewing your problem. I hope to have a response from them within 24 hours. We hope your day is going well.

To the health of your fantasy team,
Imran

**Comment by MikeSpitz** [comment] 2016-09-24 21:50
@Samze Wallace to Pitta makes sense in the above scenario as that would have made it valid. I'm guessing this occurred after the waiver wire?

We don't automatically balance teams currently. This is similar to: https://github.com/ishakir/shakitz-fantasy-football/issues/32

**Comment by MikeSpitz** [comment] 2016-09-29 08:05
^Going to close as this is a duplicate of the aforementioned issue.

**Closed by MikeSpitz** 2016-09-29 08:05 UTC
